global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: "server-pindad-monitor"

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  # - job_name: "kube-state-metrics"
  #   static_configs:
  #     - targets: ["kube-state-metrics:8080"]
  #     - targets: ["kube-state-metrics:8081"]
  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
